### ISSUE TITLE
use HDMI as console problem

### ISSUE THREAD

**Issue by embedclub** [ayufan-pine64/linux-build#12]
After making my own root file system（Ubuntu core）, how do I configure, connect HDMI, and display the character interface on the monitor?
My root file system system has been operating normally, serial port character interface is normal, serial port can be normal input command。
I have modified the dts fille and used the Command -- make menuconfig ARCH=arm64, to configure the kernel, but when I used this image it don't work out. In short， I want to use the HDMI monitor as a terminal. can you give some guide?

**Comment by ayufan** [comment]
Edit uEnv.txt.
