### ISSUE TITLE
Boot partition to small (prevents UBUNTU release upgrade)

### ISSUE THREAD

**Issue by MaikStohn** [ayufan-pine64/linux-build#22]
I just played around with the ubuntu release update which does not want to start due to insufficient space in "/boot" reported (asking for 40MB more).

Out of curiosity I booted from SD card and increased the boot partition with "gparted".

Later I was able to do a release upgrade of ubuntu using the standard commands.
It took quite a while. But 2 hours and one reboot later I had Ubuntu 16.10 running on my pinebook.
The kernel itself was NOT updated (/boot stayed 100% same). 

No problems so far with Ubuntu 16.10 and the old 3.10 kernel. All seems to work as expected.

So increasing the /boot partition by 40 MB seems to do the trick (even that it is not used).

**Comment by ayufan** [comment]
But, why ubuntu touches `/boot`? Did it try to install kernel/

**Comment by MaikStohn** [comment]
Funny thing, it did not touch /boot at all. It just wanted to have some free space there (maybe because it usually installs new kernel there).

So increasing the /boot partition to have 40 MB free just did the trick.

**Comment by pfeerick** [comment]
It's not Ubuntu per se, it is the Software Updater GUI that they use. Basically it appears to require a minimum amount of free space on /boot, which is annoying, especially when it still affects the raspberry pi as of a month ago. I resized the partition on the SD card to 100MB, and the Software Updated ran just fine, and never touched /boot, stupid thing.

**Comment by ayufan** [comment]
Ok. Thanks:)

**Comment by pfeerick** [comment]
Just give me a minute... I'll do a PR with changed partition size if you want it ;)

**Comment by ayufan** [comment]
This is solved by https://github.com/ayufan-pine64/linux-build/pull/23
