### ISSUE TITLE
Missing library in install_desktop.sh

### ISSUE THREAD

**Issue by wputnam** [ayufan-pine64/linux-build#34]
PINE64 PA641GB board with Xenial Minimal Image 0.7.5

I've tried running the desktop installer with
`sudo /usr/local/sbin/install_desktop.sh mate`
and I get the following error:
`E: Unable to locate package libmali-sunxi-utgard0-r6o0`

Searching the net for information about the package doesn't return anything useful. Was there a typo in this part, or is the package no longer available?

**Comment by ayufan** [comment]
It is correct. You have to add this ppa: https://launchpad.net/~ayufan/+archive/ubuntu/pine64-ppa/
