### ISSUE TITLE
Images not working?

### ISSUE THREAD

**Issue by fatalhalt** [ayufan-pine64/linux-build#38]
I'm having trouble booting any of the images on Pinebook, I have tried:
jessie-minimal-pine64-0.7.7-99.img.xz
xenial-i3-pinebook-bspkernel-0.7.7-99.img.xz
xenial-i3-pinebook-bspkernel-0.7.5-88.img.xz

I have used "PINE64 Installer" to write the untarred images to the microSD card. When attempting to boot I either get blinking cursor right after PINE64 splash screen or I see blank screen and power LED blinks 3 times and repeat. The only image that I had success is the official: xenial-mate-pinebook-bspkernel-0.6.2-77-sd2emmc.img.xz. I have updated my Pinebook with that but it has MATE and software compositor.

**Comment by phineasthecat** [comment]
Looks like the images built after 0.7.5 do not include U-Boot?

If you run `pine64_update_uboot.sh 0.7.7` or `pine64_update_uboot 0.7.6` from a running system, curl reports a 404. This doesn't happen with `pine64_update_kernel.sh` or `pine64_update_package.sh`.

**Comment by pfeerick** [comment]
It looks like `0.7.6` was pulled for some reason or it was never actually pushed to github, but the `simple-image-*` file which uboot is sucked out of is indeed missing in `0.7.7` :(

**Comment by fatalhalt** [comment]
Thanks for the updates, I'm waiting patiently for 0.7.8 images.

**Comment by fatalhalt** [comment]
I have tried the latest xenial-i3-pinebook-bspkernel-0.7.8-101.img.xz but Pinebook unfortunately doesn't boot with it, I get blinking power LED, Pinebook only turns on after I remove microSD card that has that image.

**Comment by itdaniher** [comment]
seeing the same thing as @fatalhalt - any update @ayufan? cheers.

**Comment by itdaniher** [comment]
I tested `xenial-i3-pinebook-bspkernel-0.7.7-99.img` - this one at least doesn't seem to be behaving properly.

**Comment by pfeerick** [comment]
@itdaniher Any particular reason you're on the 0.7.x series? It's not really ready for release (hence why it's marked pre-release still), and 0.6.2 is the current most stable [release](https://github.com/ayufan-pine64/linux-build/releases/latest) build.  

Having said that, unless you want my diagnostic script (which you can simply download anyway), there's no major changes or new features between 0.7.5 and 0.7.8, so use the 0.7.5 release. This is of course until the reason that the pinebook image isn't working for you is determined... as from the commit history and a skim of the jenkins log, it _should_ be working now..

**Comment by itdaniher** [comment]
@pfeerick was looking to play around with the new GPU stuff. I'll try 0.7.5, maybe. Thanks!

**Comment by luruke** [comment]
Same problem here, tried `jessie-minimal-pinebook-0.7.8-101.img.xz` and `stretch-minimal-pinebook-bspkernel-0.7.8-101.img.xz` but they won't boot

**Comment by ayufan** [comment]
Fixed by https://github.com/ayufan-pine64/linux-build/commit/cecca624590e8a27d641550c08ef26a1ff9ebe87. The release is on the go.
