### ISSUE TITLE
crash at startup - simple-image-sopine-0.7.10 on sopine w/ 16GB eMMC booting from 16GB uSD 

### ISSUE THREAD

**Issue by bmaya** [ayufan-pine64/linux-build#49]
quick scan of the bootlog points to ramdisk problems, ending with kernel panics.

https://pastebin.com/AWsgX4wa

changed ramdisk.img to initrd.img in uEnv.txt but still still crashed with:
[   36.976942] EXT4-fs (mmcblk0p2): couldn't mount as ext3 due to feature incompatibilities
[   36.989627] EXT4-fs (mmcblk0p2): couldn't mount as ext2 due to feature incompatibilities
[   37.005722] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)

**Comment by ayufan** [comment]
Can you test https://github.com/ayufan-pine64/linux-build/releases/tag/0.7.12?

Please ensure that you overwrite the whole eMMC/SD with the image.

**Comment by bmaya** [comment]
Tried with 7.13 and similar results.

7.15 boots fine from SD, but xenial-minimal eMMC boot produces:
https://pastebin.com/PYsWuH7f
but that's a separate issue.

**Comment by ayufan** [comment]
I tried on eMMC it boots fine.

**Comment by ayufan** [comment]
You might have different eMMC.

**Comment by bmaya** [comment]
I seem only have the 16GB FORESEE modules. 

I might have another 64GB somewhere -

**Comment by ayufan** [comment]
@bmaya Can you create a new issue to track eMMC? Please post there a model number of memory chip with the informations that you have now.

**Comment by bmaya** [comment]
tried with 3x ncembsf9-16g and 1x ncembsf9-64g (same as yours) and still had the same boot problem. 

both with removing the SD card first, and with boot0 disabled on the SD and SD card present.
