### ISSUE TITLE
E: Package 'glmark2-es2' has no installation candidate

### ISSUE THREAD

**Issue by jhalbrecht** [ayufan-pine64/linux-build#68]
Got out my pine A64+ for the first time since the kickstarter ended.

I booted `stretch-minimal-pine64-bspkernel-0.7.30-140.img.xz` and logged in via ssh. Works.

I wanted to try out the desktop. Is this the prefered way to install it? `/usr/local/sbin/install_desktop.sh lxde`

I'm getting the errors 
`E: Package 'glmark2-es2' has no installation candidate`
`E: Package 'chromium-browser' has no installation candidate`

`root@pine64:~# /usr/local/sbin/install_desktop.sh lxde
Hit:1 http://security.debian.org stretch/updates InRelease
Hit:2 http://ppa.launchpad.net/longsleep/ubuntu-pine64-flavour-makers/ubuntu xen                                                                             ial InRelease
Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Hit:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
Hit:5 http://ppa.launchpad.net/ayufan/pine64-ppa/ubuntu xenial InRelease
Get:6 http://deb.ayufan.eu/orgs/ayufan-pine64/releases  InRelease [1327 B]
Hit:7 http://cdn-fastly.deb.debian.org/debian stretch Release
Fetched 1327 B in 2s (586 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
26 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package chromium-browser is not available, but is referred to by another package                                                                             .
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package glmark2-es2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'glmark2-es2' has no installation candidate
E: Package 'chromium-browser' has no installation candidate
root@pine64:~#
`

**Comment by jhalbrecht** [comment]
If I get a desktop installed is HDMI still a problem? See;  hdmi not functional in prerelease #55

**Comment by frdlt** [comment]
I received these same errors. When these are commented out of the /install_desktop.sh file, error #71 occurs.

**Comment by frdlt** [comment]
I've updated #71 with a solution that will probably also solve your issue in the OP.

**Comment by desaiamogh** [comment]
I put this up after installing mine.  It really helps to have clear instructions around a problem for newbies.
https://amoghdesai.com/technology/how-to-resolve-errors-and-install-desktop-environment-on-pine64-a/

hope ayufan will update the script to fix this issue in next release.

**Comment by jhalbrecht** [comment]
Thanks @desaiamogh 

FWIW I've moved over to [Armbian](http://wiki.pine64.org/index.php/Pine_A64_Software_Release#Armbian)
