### ISSUE TITLE
Default desktop and lock screen background for Mate Desktop

### ISSUE THREAD

**Issue by pgmy64** [ayufan-pine64/linux-build#9]
Can you use Pinebook background image as default desktop and lock screen background?  The reason is due to Ubuntu trademark concern.

We are going to prepare a build for production in the week of 22nd May 2017 and hope the coming build will include the above changes so that we can just pass Community Build to production team for upcoming Pinebook shipment.

Thanks.

**Comment by ayufan** [comment]
@pgmy64 

We have images already with the image, we only need mate-specific configuration. Could your team figure out what we have to run or where we should store default background? It should be fairly easy fix.

**Comment by pgmy64** [comment]
Please help to add below command in your script to set the default desktop background

dconf write /org/mate/desktop/background/picture-filename "'/usr/share/backgrounds/ubuntu-mate-pinebook/Pinebook-Wallpaper-6.jpg'"

Meanwhile, we will try to check how to change lockscreen background with script.  Thanks.

**Comment by pgmy64** [comment]
Please help to add below command to change the default login screen background.  Thanks.

sudo sed -i 's/#background=/background=\/usr\/share\/backgrounds\/ubuntu-mate-pinebook\/Pinebook-Wallpaper-6.jpg/g' /etc/lightdm/lightdm-gtk-greeter.conf

**Comment by pgmy64** [comment]
@ayufan 

Do you have better way to set the default desktop wallpaper to Pinebook-Wallpaper-6.jpg?

Thanks.

**Comment by ayufan** [comment]
It doesn't work from command line.

**Comment by pgmy64** [comment]
@ayufan 

The dconf database is store in user folder

~/.config/dconf/user

**Comment by ayufan** [comment]
Yes, but we need to make a global config for that.

**Comment by ayufan** [comment]
@pgmy64 The login background is fixed. Do you have an idea how to fix user background?

**Comment by pgmy64** [comment]
@ayufan I don't have any idea how to fix that at this moment.

**Comment by pfeerick** [comment]
Maybe this will do it?

```dconf write /org/mate/desktop/background/picture-filename "'<path-to-file>'" ```

i.e.

```dconf write /org/mate/desktop/background/picture-filename "'/usr/share/backgrounds/ubuntu-mate-pinebook/Pinebook-Wallpaper-6.jpg'" ```

(baring any transposition errors from re-typing that from what is on my pinebook screen! :-O

**Comment by ayufan** [comment]
It requires to be run in X11 context

**Comment by pfeerick** [comment]
hm... damn

how about 
```dbus-launch --exit-with-session gsettings set org.mate.background picture-filename "'/usr/share/backgrounds/ubuntu-mate-pinebook/Pinebook-Wallpaper-6.jpg'"```
